export default {
	"pages": {
		"root": {
			"pageUrl": "root",
			"name": "root",
			"children": [
				"6679067bfdcae00021e3c714",
				"6679067bfdcae00021e3c718"
			],
			"id": "root"
		},
		"6679067bfdcae00021e3c714": {
			"id": "6679067bfdcae00021e3c714",
			"name": "404",
			"pageUrl": "404"
		},
		"6679067bfdcae00021e3c718": {
			"id": "6679067bfdcae00021e3c718",
			"name": "index",
			"pageUrl": "index",
			"seo": {
				"title": ""
			}
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {
			"background": ""
		},
		"seo": {
			"title": "About Me Profilo",
			"og:image": "https://uploads.quarkly.io/6679067bfdcae00021e3c6f6/images/channels4_profile.jpg?v=2024-06-24T06:47:59.681Z",
			"og:title": "About Me Profilo",
			"favicon_32px": "https://uploads.quarkly.io/6679067bfdcae00021e3c6f6/images/channels4_profile.jpg?v=2024-06-24T06:47:59.681Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/6679067bfdcae00021e3c6f6/images/channels4_profile.jpg?v=2024-06-24T06:47:59.681Z",
			"background_win10": "#F2EFEA",
			"description": "Know me better",
			"og:description": "get to know me better",
			"favicon_apple_152px": "https://uploads.quarkly.io/6679067bfdcae00021e3c6f6/images/channels4_profile.jpg?v=2024-06-24T06:47:59.681Z",
			"robotsFileType": "autogenerated"
		}
	}
}